openapi: 3.0.9
info:
  title: Payment API
  contact:
    email: thevivek2@gmail.com
  version: 1.0.0

paths:
  /api/v1/users:
    post:
      tags:
        - User
      summary: Create User
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VoilationResource'

  /api/v1/accounts/{accountNumber}:
    get:
      tags:
        - Account
      summary: Get Account Detail
      operationId: get
      parameters:
        - name: accountNumber
          in: path
          description: Account Number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/AccountResource'
    patch:
      tags:
        - Account
      summary: Partial Update of Account
      operationId: patch
      parameters:
        - name: accountNumber
          in: path
          description: Account Number
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountUpdateRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResource'

  /api/v1/accounts/{accountNumber}/history:
    get:
      tags:
        - Account
      summary: Get Account History
      operationId: getHistory
      parameters:
        - name: accountNumber
          in: path
          description: Account Number
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/AccountResource'

components:
  schemas:
    UserRequest:
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 255
          example: 'Vivek Adhikari'
        email:
          type: string
          minLength: 2
          maxLength: 255
          format: email
          example: 'thevivek2@gmail.com'
        mobileNumber:
          type: string
          example: '2222222222'
          minLength: 10
      required:
        - name
        - email
        - mobileNumber

    UserResource:
      properties:
        uuid:
          type: string
          example: '123e4567-e89b-12d3-a456-426614174000'
        status:
          type: string
          example: 'CREATED'
      required:
        - uuid
        - status

    VoilationResource:
      properties:
        field:
          type: string
          example: 'email'
        message:
          type: string
          example: 'This is required'
      required:
        - message

    AccountResource:
      properties:
        accountNumber:
          type: string
          example: '22222'
        status:
          $ref: '#/components/schemas/AccountStatus'

    AccountStatus:
      type: string
      enum:
        - OPEN
        - CLOSED

    AccountUpdateRequest:
      properties:
        status:
          $ref: '#/components/schemas/AccountStatus'


