openapi: 3.0.9
info:
  title: Payment API
  contact:
    email: thevivek2@gmail.com
  version: 1.0.0

paths:
  /api/v1/users:
    post:
      tags:
        - User
      summary: Create User
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResource'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VoilationResource'

components:
  schemas:
    UserRequest:
      properties:
        name:
          type: string
          example: 'Vivek Adhikari'
        email:
          type: string
          example: 'thevivek2@gmail.com'
        mobileNumber:
          type: string
          example: '22222'

    UserResource:
      properties:
        uuid:
          type: string
          example: '2222'
        status:
          type: string
          example: 'CREATED'

    VoilationResource:
      properties:
        field:
          type: string
          example: 'email'
        message:
          type: string
          example: 'This is required'

